name: Generate Go Documentation

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Install gomarkdoc
      run: go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

    - name: Create doc directory
      run: mkdir -p doc

    - name: Generate documentation
      run: gomarkdoc -o doc/readme.md

    - name: Check for changes
      id: git-check
      run: |
        git add doc/
        git diff --staged --quiet || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Setup branch and commit
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        branch_name="docs/update-${{ github.run_id }}"
        git checkout -b $branch_name
        git commit -m "docs: Update Go documentation"
        git push origin $branch_name

    - name: Create Pull Request
      if: steps.git-check.outputs.changed == 'true'
      run: |
        gh pr create \
          --base main \
          --head "docs/update-${{ github.run_id }}" \
          --title "docs: Update Go documentation" \
          --body "Auto-generated documentation update" \
          --label "documentation"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
