name: Generate Go Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Install godoc
      run: go install golang.org/x/tools/cmd/godoc@latest

    - name: Create docs directory
      run: mkdir -p docs

    - name: Generate documentation
      run: |
        nohup godoc -http=:6060 &
        sleep 5
        wget -r -np -nH --cut-dirs=1 -P docs/ http://localhost:6060

    - name: Commit and push documentation
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Update Go documentation [skip ci]" || echo "No changes to commit"
        git push
