name: Generate Go Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Install gomarkdoc
      run: go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

    - name: Create doc directory
      run: mkdir -p doc

    - name: Generate documentation
      run: gomarkdoc -dir . -o doc

    - name: Commit and push documentation
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "Update Go documentation [skip ci]" || echo "No changes to commit"
        git push
