name: Generate Swagger Documentation

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Install Swagger
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Create docs directory
      run: mkdir -p docs

    - name: Generate Swagger documentation
      run: swag init

    - name: Check for changes
      id: git-check
      run: |
        git add docs/
        git diff --staged --quiet || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Setup branch and commit
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        branch_name="docs/swagger-update-${{ github.run_id }}"
        git checkout -b $branch_name
        git commit -m "docs: Update Swagger documentation"
        git push origin $branch_name

    - name: Create Pull Request
      if: steps.git-check.outputs.changed == 'true'
      run: |
        gh pr create \
          --base main \
          --head "docs/swagger-update-${{ github.run_id }}" \
          --title "docs: Update Swagger documentation" \
          --body "Auto-generated Swagger documentation update" \
          --label "documentation"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
